### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by racaljk** [racaljk/pyann#2]
- [ ] complete `bpnn` demo for classifying iris data
- [ ] add more network structure such cnn,rnn,etc
- [ ] create documents for each network model

**Comment by racaljk** [comment]
no3 done
